/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import service.ReparationService;
import javax.swing.JInternalFrame;
/**
 *
 * @author hp
 */

public class GraphiqueForm extends JInternalFrame {

    /**
     * Creates new form GraphiqueForm
     */
   public GraphiqueForm() {
    initComponents();
  setClosable(true);
    setIconifiable(true);
    setMaximizable(true);

    afficherGraphique();   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void afficherGraphique() {

    ReparationService service = new ReparationService();
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    List<Object[]> data = service.gettotalcoutsmensuels();

    for (Object[] row : data) {
        int mois = (int) row[0];
        double total = ((Number) row[1]).doubleValue();
        dataset.addValue(total, "Total Coût", "Mois " + mois);
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Total des coûts mensuels",
            "Mois",
            "Montant (DH)",
            dataset
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(800, 500));

    getContentPane().removeAll();
    setLayout(new java.awt.BorderLayout());
    add(chartPanel, java.awt.BorderLayout.CENTER);
   
}
    /**
     * @param args the command line arguments
     */
 
        /* Set the Nimbus look and feel */
  public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {

            
            LoginFrame login = new LoginFrame();
            login.setVisible(true);

        }
    });
}      
        /* Create and display the form */
   }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

