package app;

import entities.Reparation;
import service.ReparationService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.util.List;

public class ReparationFrame extends JInternalFrame {
    private ReparationService service = new ReparationService();

    public ReparationFrame() {
        super("", true, true, true, true); 
        initComponents();
        loadReparations();
        setSize(800, 700);
         
      
        setVisible(true);
    
    }

    private void loadReparations() {
        try {
            List<Reparation> list = service.findAll();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            for (Reparation r : list) {
                model.addRow(new Object[]{
                        r.getId(),
                        r.getVehiculeId(),
                        r.getDate(),
                        r.getType(),
                        r.getCout()
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblType = new javax.swing.JPanel();
        lblVehiculeId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCout = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnActualiser = new javax.swing.JButton();
        txtCout = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        txtVehiculeId = new javax.swing.JTextField();
        jTableReparation = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gestions Des Reparations");

        lblType.setBackground(new java.awt.Color(255, 255, 255));
        lblType.setBorder(new javax.swing.border.MatteBorder(null));

        lblVehiculeId.setText("Vehicule ID :");

        jLabel2.setText("Type :");

        lblDate.setText("Date :");

        lblCout.setText("Cout :");

        btnAjouter.setBackground(new java.awt.Color(0, 51, 255));
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(0, 102, 51));
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setBackground(new java.awt.Color(255, 51, 51));
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnActualiser.setBackground(new java.awt.Color(0, 0, 255));
        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblTypeLayout = new javax.swing.GroupLayout(lblType);
        lblType.setLayout(lblTypeLayout);
        lblTypeLayout.setHorizontalGroup(
            lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTypeLayout.createSequentialGroup()
                .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(lblTypeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjouter)
                        .addGap(117, 117, 117)
                        .addComponent(btnModifier)
                        .addGap(155, 155, 155)
                        .addComponent(btnSupprimer)
                        .addGap(60, 60, 60))
                    .addGroup(lblTypeLayout.createSequentialGroup()
                        .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblTypeLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblVehiculeId)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTypeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)))
                        .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVehiculeId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate)
                            .addComponent(lblCout))
                        .addGap(30, 30, 30)))
                .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTypeLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnActualiser)
                        .addGap(90, 90, 90))
                    .addGroup(lblTypeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        lblTypeLayout.setVerticalGroup(
            lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTypeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtVehiculeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVehiculeId)
                        .addComponent(lblDate))
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCout)
                    .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(lblTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer)
                    .addComponent(btnActualiser))
                .addGap(25, 25, 25))
        );

        jTableReparation.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "VehiculeId", "Date", "Type", "Cout"
            }
        ));
        jTableReparation.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTableReparation)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTableReparation, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
        Reparation r = new Reparation();

        r.setVehiculeId(Integer.parseInt(txtVehiculeId.getText()));
        java.util.Date utilDate = txtDate.getDate();
        LocalDate localDate = utilDate.toInstant()
        .atZone(java.time.ZoneId.systemDefault())
        .toLocalDate();

         r.setDate(localDate);
        r.setType(txtType.getText());
        r.setCout(Double.parseDouble(txtCout.getText()));

        service.create(r);
        loadReparations();

        txtVehiculeId.setText("");
           txtDate.setDate(null);
        txtType.setText("");
        txtCout.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
   }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
int row = jTable1.getSelectedRow();

    if (row >= 0) {
        int id = (int) jTable1.getValueAt(row, 0);

        try {
            service.supprimer(id);
            loadReparations();
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Sélectionnez une réparation");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
int row = jTable1.getSelectedRow();

    if (row >= 0) {
        try {
            Reparation r = new Reparation();

            r.setId((int) jTable1.getValueAt(row, 0));
            r.setVehiculeId(Integer.parseInt(txtVehiculeId.getText()));
            java.util.Date utilDate = txtDate.getDate();
            LocalDate localDate = utilDate.toInstant()
        .atZone(java.time.ZoneId.systemDefault())
        .toLocalDate();

r.setDate(localDate);
            r.setType(txtType.getText());
            r.setCout(Double.parseDouble(txtCout.getText()));

            service.modifier(r);
            loadReparations();

        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Sélectionnez une réparation");
      }        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed
  
    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
     loadReparations();        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualiserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReparationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReparationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReparationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReparationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       new ReparationFrame().setVisible(true);
         }
         
       });
      
     }           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jTableReparation;
    private javax.swing.JLabel lblCout;
    private javax.swing.JLabel lblDate;
    private javax.swing.JPanel lblType;
    private javax.swing.JLabel lblVehiculeId;
    private javax.swing.JTextField txtCout;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtVehiculeId;
    // End of variables declaration//GEN-END:variables
}
